version: '0.1.0-alpha-{build}'
image: Visual Studio 2017
clone_depth: 10
skip_tags: true

branches:
  only:
  - master

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true  # Don't download unneeded packages
  DOTNET_CLI_TELEMETRY_OPTOUT: true        # Don't send telemetry
  matrix:
    - nodejs_version: "6.10.2"
    - nodejs_version: "7"
platform: 
  - x86
  - x64 


install:
  - ps: Install-Product node $env:nodejs_version $env:platform 
  - npm install -g npm --silent
  - npm install -g typescript
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
      Install-Module InvokeBuild -RequiredVersion 3.2.1 -Scope CurrentUser -Force | Out-Null
build_script:
  - ps: Invoke-Build

# TODO: The build script will take care of the tests
test_script: 
  - node --version
  - npm --version
